#!/usr/bin/env python3

import socket

# Create a socket object
client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# Get the server IP and port
server_ip = 'localhost'
server_port = 12345

# Connect to the server
client_socket.connect((server_ip, server_port))

def send_message(message):
    client_socket.sendall(message.encode())
    response = client_socket.recv(1024)
    print(response.decode())



command = int(input("Select commnad\n1. Register\n2. Login\n"))

if command == 1:
    print("Register...")
    username = input("Enter an username\n")
    password = input("Enter a password\n")
    send_message(f'register:{username},{password}')
if command == 2:
    username = input("Enter an username\n")
    password = input("Enter a password\n")
    send_message(f'login:{username},{password}')
    asd = int(input("1. write a message\n"
                    "2.read messages\n"
                    "3.delete messages\n"
                    "4.add friend\n"
                    "5.remove friend (Not W)\n"
                    "6.list friends\n"
                    "7.create group (Not W)\n"
                    "8.add group member\n"
                    "9.remove group member\n"
                    "10.list group members\n"
                    "11.send group message\n"
                    "12.read group messages\n"
                    "Enter the command\n"))
    if asd == 1:
        print("Write a message...")
        receiver = input("Enter the receiver's username\n")
        message = input("Enter the message\n")
        send_message(f'write_message:{username},{receiver},{message}')
    elif asd == 2:
        print("Read messages...")
        send_message(f'read_messages:{username}')
    elif asd == 3:
        print("Delete messages...")
        send_message(f'delete_messages:{username}')
    elif asd == 4:
        print("add friend...")
        friend = input("Enter the friend's username\n")
        send_message(f'add_friend:{username},{friend}')
    elif asd == 5:
        print("remove friend...")
        friend = input("Enter the friend's username\n")
        send_message(f'remove_friend:{username},{friend}')
    elif asd == 6:
        print("list friends...")
        send_message(f'list_friends:{username}')
    elif asd == 7:
        print("create group...")
        group_name = input("Enter the group name\n")
        send_message(f'create_group:{group_name}')
    elif asd == 8:
        print("add group member...")
        group_id = input("Enter the group id\n")
        member = input("Enter the member's username\n")
        send_message(f'add_group_member:{group_id},{member}')
    elif asd == 9:
        print("remove group member...")
        group_name = input("Enter the group id\n")
        member = input("Enter the member's username\n")
        send_message(f'remove_group_member:{username},{group_name},{member}')
    elif asd == 10:
        print("list group members...")
        group_id = input("Enter the group id\n")
        send_message(f'list_group_members:{group_id}')
    elif asd == 11:
        print("send_group_message")
        group_name = input("Enter the group id\n")
        message = input("Enter the message\n")
        send_message(f'send_group_message:{group_name},{username},{message}')
    elif asd == 12:
        print("read_group_messages")
        group_name = input("Enter the group id\n")
        send_message(f'read_group_messages:{group_name}')        
        
    else:
        print("Invalid command")

# Close the connection
client_socket.close()

